version: '2'
services:
  dns:
    build:
      context: .
      dockerfile: Dockerfile
    restart: never
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/udp"
    cap_add:
      - NET_ADMIN